In [2]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt

In [26]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512,10)
        )
        
        def forward(self, x):
            x = self.flatten(x)
            logits = self.linear_relu_stack(x)
            return logits

model = Network()

In [41]:
rnn = nn.LSTM(5, 5, 1)
input = torch.randn(2, 2, 5)
h0 = torch.randn(1, 2, 5)
c0 = torch.randn(1, 2, 5)

In [42]:
output, (hn, cn) = rnn(input, (h0,c0))

In [43]:
output

tensor([[[-0.0934,  0.0777,  0.1803,  0.0044,  0.2903],
         [ 0.1954,  0.4706, -0.1326, -0.1034, -0.1427]],

        [[ 0.1579,  0.0613, -0.0034, -0.0400,  0.1895],
         [ 0.2817,  0.3172,  0.0439, -0.1374, -0.2238]]],
       grad_fn=<StackBackward0>)

In [44]:
hn

tensor([[[ 0.1579,  0.0613, -0.0034, -0.0400,  0.1895],
         [ 0.2817,  0.3172,  0.0439, -0.1374, -0.2238]]],
       grad_fn=<StackBackward0>)

In [45]:
cn

tensor([[[ 0.2061,  0.1349, -0.0059, -0.0759,  0.4401],
         [ 0.6616,  0.8498,  0.0761, -0.2348, -0.7976]]],
       grad_fn=<StackBackward0>)

In [14]:
m = nn.Linear(20, 30)
input = torch.randn(128, 20)
output = m(input)
print(output.size())

torch.Size([128, 30])


In [30]:
?nn.LSTM